### ISSUE TITLE
perhaps use spawn instead of fork

### ISSUE THREAD

**Issue by jjb** [seamusabshere/unix_utils#1] opened 2012-03-02 23:10 UTC
Open3 uses fork(2) to create the process running the system command, which will replicate the entire environment (all the memory) while the command is running. So, a 100 meg ruby program that invokes `echo foo` will be using 200 megs until that command is finished.

An alternative is to use posix_spawn(2):

https://github.com/rtomayko/posix-spawn

**Comment by seamusabshere** [comment] 2012-03-02 23:14
A couple reasons I chose `open3` for this release:
- it's in the ruby standard lib, so no extra gem requirements
- I had some trouble with file handles with posix_spawn and jruby

If you can get it working with posix-spawn on JRuby 1.6.7+, I'll be ok with switching. Thanks!

**Comment by jjb** [comment] 2012-03-02 23:18
Gotcha :)

On Fri, Mar 2, 2012 at 6:14 PM, Seamus Abshere <
reply@reply.github.com

**Comment by seamusabshere** [comment] 2012-03-06 15:58
hey @jjb,

I created a branch that uses posix-spawn:

https://github.com/seamusabshere/unix_utils/tree/posix-spawn

On the one hand, it seems to be **faster** (1.7s vs 1.9s on my MB Pro) just blindly running `rake` (the tests) over and over again.

On the other hand, it seems to be **MUCH slower** when I try what I did in https://gist.github.com/1950707.

```
alzabo0:~ $ cd ~/Documents/TomTom/HOME/Download/complete/map/USA__Canada___Mexico
alzabo0:~/Documents/TomTom/HOME/Download/complete/map/USA__Canada___Mexico $ time ruby -r'unix_utils' -e 'p UnixUtils.shasum("USA_Canada_and_Mexico_P.zip", 256)'

real  0m22.956s
user  0m13.242s
sys 0m0.990s
alzabo0:~/Documents/TomTom/HOME/Download/complete/map/USA__Canada___Mexico $ time ruby -r'unix_utils' -e 'p UnixUtils.shasum("USA_Canada_and_Mexico_P.zip", 256)'
"3c72f24f258c762b2f7061debadb9a6e997bd5353c99966cb095d865a4ea2b89"

real  0m24.236s
user  0m13.578s
sys 0m0.962s
alzabo0:~/Documents/TomTom/HOME/Download/complete/map/USA__Canada___Mexico $ time ruby -r'unix_utils' -e 'p UnixUtils.shasum("USA_Canada_and_Mexico_P.zip", 256)'
"3c72f24f258c762b2f7061debadb9a6e997bd5353c99966cb095d865a4ea2b89"

real  0m29.079s
user  0m13.781s
sys 0m1.024s
```

Maybe you could work with @bkutil to diagnose this? In particular, what's the memory (as opposed to speed) impact?

**Comment by jjb** [comment] 2012-03-07 01:37
cool!

To measure memory usage you can use ruby-prof. You need to have a patched ruby interpreter to support this feature. REE comes patched for this by default. So you can at least test under 1.8.7 easily, see if there is progress there, and if so maybe build a special 1.9 for it (i don't know how, prob easy to google)

```
$ rbenv shell ree-1.8.7-2012.02
$ gem install ruby-prof
$ rbenv rehash
$ ruby-prof --mode=memory foo.rb
```

**Comment by seamusabshere** [comment] 2012-03-07 16:01
hey,

(First of all, thanks for the ruby-prof tip... it's one of those things you have to see somebody else do once :) )

I committed some ruby-prof results in https://github.com/seamusabshere/unix_utils/commit/21db1050025e965a70c6a5a6e4e0701af112e0e1, but it doesn't seem to be capturing the memory used by forking in open3.

Do you know how to use valgrind? oh @bkutil ... any advice?

Best,
Seamus

**Comment by jjb** [comment] 2012-03-07 17:19
Ironically, that's probably because REE uses copy-on-write so it's not going to have the memory problem when forking :)

**Comment by tmm1** [comment] 2012-03-16 21:46
posix-spawn has no effect on the memory usage of your script, so valgrind and other memory profilers will show no difference.

The only advantage of posix-spawn is that, on Linux, it is faster to than fork(2) when called from large parent processes. This means fork will take 10-30ms per call if your ruby process is 500mb, while posix_spawnp(2) will always be extremely fast and constant time.

The posix-spawn repo contains a benchmark which exposes this. To replicate you need to increase the size of your parent process and spawn processes in a loop, so the fork overhead adds up.

**Comment by jjb** [comment] 2012-03-16 22:08
@tmm1 What you are saying conflicts with the first paragraph of the posix-spawn readme https://github.com/rtomayko/posix-spawn#readme

What are you basing this on? Are you sure your observations aren't from a copy-on-write ruby runtime?

**Comment by tmm1** [comment] 2012-03-16 22:28
> `fork(2)` calls slow down as the parent process uses more memory due to the need to copy page tables.

I don't see the conflict. This is simply stating that as the parent proeess gets larger, calls to fork take longer.

**Comment by tmm1** [comment] 2012-03-16 22:29
The COW behavior in REE is completely un-related to posix-spawn.

**Comment by seamusabshere** [comment] 2012-03-16 22:30
@jjb I should mention @tmm1 is one of the authors of posix-spawn and I asked him to take a look at this.

**Comment by jjb** [comment] 2012-03-16 22:41
Oh, glad you mentioned that :-D

Well then I think the above conflicts with my understanding from @jstorimer's book, http://workingwithunixprocesses.com

[will that mention summon him even though he wasn't in the thread? Let's see...]

**Comment by tmm1** [comment] 2012-03-17 00:59
The issue is essentially that fork() makes copies of all the page tables. In a large linux process, there can be hundreds or thousands of these since the page size is very small by default.

In the fork+exec case, there's is no point in making copies of these page tables, since the process is going to exec right after the fork and does not need access to the parent's memory.

Using posix_spawn instead of fork+exec avoids the fork overhead by using vfork internally.

**Comment by jjb** [comment] 2012-03-17 04:42
Thanks for the explanation.

What does "makes copies of all the page tables" mean?

**Comment by tmm1** [comment] 2012-03-17 04:54
The page table maps addresses to actual pages of memory. This is what allows for COW. When forking, the entire contents of memory are _not_ copied. Instead, only the page table is replicated.

Since the page table starts out as a copy, the child can refer to the same pages of memory as the parent and read them directly. When writing to a page, the child finally makes an actual copy of the memory and updates its page table to point to this newly modified version of that page.

Again, this is only useful when the parent and child are trying to share memory. When you call exec immediately after fork, you are simply creating a new process and could care less about replicating page tables into the child. This is where vfork and posix_spawnp provide an advantage.

This is entirely Linux specific, and it only really has an effect on large parent process that are performing a large number of forks. Eventually, linux will support hugetlb by default and this will be a non-issue.

**Comment by jjb** [comment] 2012-03-17 05:13
I see. But that seems to align with my previous understanding. is this
wrong: When forking using a ruby that does ****_not**_ support CoW (such as
all MRI versions), it's not just the page tables that are copied, but all
of the memory of the original process.

**Comment by tmm1** [comment] 2012-03-17 05:25
> : When forking using a ruby that does ****_not**_ support CoW (such as all MRI versions), it's not just the page tables that are copied, but all of the memory of the original process.

No. Linux always uses COW when forking. MRI breaks COW by writing to every single page during GC. REE fixes this by moving the mark bit outside of the ruby object definition to a separate mark table. That way objects can be marked and swept without modifying the page of memory where they live.

**Comment by jstorimer** [comment] 2012-03-18 03:09
@seamusabshere I tried your example with a smaller file (~20MB) and didn't get the same behaviour. In my case the posix-spawn version was actually faster. Not sure if that helps, but interesting.

@jjb I re-read that section of my book and it seems in line with what @tmm1 is saying. Feel free to shoot me an email if you want to chat more about it and I'd be happy to help.

**Comment by seamusabshere** [comment] 2012-03-19 16:19
posix-spawn seems to be working great, so I took your suggestion @jjb and swapped it in.

https://github.com/seamusabshere/unix_utils/commit/19d073ff0666239388ecdd85319b9a5e9cda6861

**Closed as completed by seamusabshere** 2012-03-19 16:19 UTC

**Comment by jjb** [comment] 2012-03-19 20:32
@seamusabshere cool

@tmm1:

> No. Linux always uses COW when forking. MRI breaks COW by writing to every single page during GC. REE fixes this by moving the mark bit outside of the ruby object definition to a separate mark table. That way objects can be marked and swept without modifying the page of memory where they live.

So, given that, in MRI won't posix-spawn use less memory than fork in many situations?

**Comment by jjb** [comment] 2012-04-13 18:37
@jstorimer check out the question I asked @tmm1 above

**Comment by jstorimer** [comment] 2012-04-16 04:21
@jjb posix-spawn _will_ use less memory than fork because it doesn't need to copy any of the page tables.

posix-spawn is a replacement for fork+exec. When you fork(), even if you plan to exec() another program like `curl`, the kernel is oblivious to your intentions. In the new process it effectively copies all of the memory that was in use in the calling process (Ruby interpreter, source code, current state, etc). 

Obviously the new process won't need any of that if it's just to become `curl`. posix-spawn cuts down the overhead by creating a new process that doesn't inherit the page tables of its parent. Other fork() semantics, preservation of open file descriptors, etc. are maintained. Check posix_spawn(2) for all the details.

hth

**Comment by seamusabshere** [comment] 2012-04-16 16:16
thanks @jstorimer @jjb and @tmm1 for making this a very informative discussion!
